### ISSUE TITLE
Add a way to disable download-sources option in chainbuild

### ISSUE THREAD

**Issue by mnencia** [alanfranz/docker-rpm-builder#38]
First of all, thanks for implementing chainbuild command. It is very useful.

In my use case I have already downloaded the sources (which are some private testing files) and I need to build them using chainbuild. 
To make it working I tried to modify the spec file removing the full URLs and leaving only the file name, but as result it tries to spawn wget with no url at all.

```
2017-03-02T19:33:22+0100 INFO [drb.commands.dir] Now downloading sources
2017-03-02T19:33:22+0100 INFO [drb.downloadsources] Downloading additional sources
2017-03-02T19:33:23+0100 ERROR [UserExceptionTransformer] Full catched exception:
Traceback (most recent call last):
  File "/Users/mnencia/prj/ci/docker-rpm-builder/drb/commands/chainbuild.py", line 131, in chainbuild
    downloadsources(source_directory, specfile, image)
  File "/Users/mnencia/prj/ci/docker-rpm-builder/drb/downloadsources.py", line 48, in downloadsources
    download_files(urls, source_directory)
  File "/Users/mnencia/prj/ci/docker-rpm-builder/drb/downloadsources.py", line 87, in download_files
    sp("{wget} --directory-prefix={download_dir} --timestamping {joined_urls}", **locals())
  File "/Users/mnencia/prj/ci/docker-rpm-builder/drb/downloadsources.py", line 37, in sp
    raise SpawnedProcessError(retcode, fullcmd, output=output, error=error)
SpawnedProcessError: Command '/usr/local/bin/wget --directory-prefix=/Users/mnencia/test/rpm --timestamping ' returned non-zero exit status 1:

wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.


Error: it was impossible to download at least one source file
```

**Comment by alanfranz** [comment]
v1.37 was released.
