### ISSUE TITLE
Get the KeyError: u'ITERATION' when running on Mac Sierra

### ISSUE THREAD

**Issue by macbeth76** [alanfranz/docker-rpm-builder#46]
When I try running this from the examples folder but selftest says things are ok.

`/User/demouser/dockers/docker-rpm-builder/devenv/bin/docker-rpm-builder genspec ./tmux.spectemplate ./tmux.spec`

```
Traceback (most recent call last):
  File "/User/demouser/dockers/docker-rpm-builder/devenv/bin/docker-rpm-builder", line 9, in <module>
    load_entry_point('docker-rpm-builder==0.99.dev0', 'console_scripts', 'docker-rpm-builder')()
  File "/User/demouser/dockers/docker-rpm-builder/devenv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/User/demouser/dockers/docker-rpm-builder/devenv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/User/demouser/dockers/docker-rpm-builder/devenv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/User/demouser/dockers/docker-rpm-builder/devenv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/User/demouser/dockers/docker-rpm-builder/devenv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/User/demouser/dockers/docker-rpm-builder/drb/commands/genspec.py", line 44, in genspec
    rendered_filename = SpecTemplate.from_path(spectemplate).render(os.environ)
  File "/User/demouser/dockers/docker-rpm-builder/drb/spectemplate.py", line 46, in render
    with_substitutions = self._ddtemplate.substitute(substitution_mapping).encode("utf-8")
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.py", line 176, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.py", line 166, in convert
    val = mapping[named]
  File "/User/demouser/dockers/docker-rpm-builder/devenv/bin/../lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: u'ITERATION'
```

**Comment by alanfranz** [comment]
Hello @macbeth76,
the example spectemplate uses variable interpolation. One example
interpolated variable is ITERATION. That error means you don't have an
ITERATION variable defined in your bash.

Admittedly, that error could be better explained to the user; I'll see what
I can do in a future release.

**Comment by alanfranz** [comment]
Consider becoming a docker-rpm-builder developer: https://github.com/alanfranz/docker-rpm-builder/issues/51
