### ISSUE TITLE
download-sources in combination with %package section(s)

### ISSUE THREAD

**Issue by hunter-nl** [alanfranz/docker-rpm-builder#48]
When I use Source0 and Source1 with an URL and have one or more %package sections in my spec file, than docker-rpm-builder with --download-sources will fail with:
```2017-12-17T16:15:36+0100 INFO [drb.commands.dir] Now downloading sources
2017-12-17T16:15:36+0100 INFO [drb.downloadsources] Downloading additional sources
2017-12-17T16:15:36+0100 DEBUG [Docker] Now executing:
/bin/docker run --rm alanfranz/drb-epel-7-x86-64:latest which rpmbuild

2017-12-17T16:15:37+0100 DEBUG [Docker] Now executing:
/bin/docker run --rm --volume=/tmp/drb-temp.IHMx11:/tmp/drb-temp.IHMx11:z,ro alanfranz/drb-epel-7-x86-64:latest /usr/bin/rpmbuild --nodeps -bp /tmp/drb-temp.IHMx11/lua53.spec

2017-12-17T16:15:37+0100 ERROR [UserExceptionTransformer] Full catched exception:
Traceback (most recent call last):
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/commands/dir.py", line 140, in dir
    downloadsources(source_directory, specfile, image)
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/downloadsources.py", line 46, in downloadsources
    lines = get_spec_with_resolved_macros(specfilename, target_image)
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/downloadsources.py", line 69, in get_spec_with_resolved_macros
    tempspec_path).do_run()
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/docker.py", line 75, in do_run
    return self._run().strip()
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/docker.py", line 95, in _run
    raise SpawnedProcessError(retcode, fullcmd, output=output, error=error)
SpawnedProcessError: Command '/bin/docker run --rm --volume=/tmp/drb-temp.IHMx11:/tmp/drb-temp.IHMx11:z,ro alanfranz/drb-epel-7-x86-64:latest /usr/bin/rpmbuild --nodeps -bp /tmp/drb-temp.IHMx11/lua53.spec' returned non-zero exit status 1:

error: Package already exists: %package devel


Error: it was impossible to download at least one source file
Command '/bin/docker run --rm --volume=/tmp/drb-temp.IHMx11:/tmp/drb-temp.IHMx11:z,ro alanfranz/drb-epel-7-x86-64:latest /usr/bin/rpmbuild --nodeps -bp /tmp/drb-temp.IHMx11/lua53.spec' returned non-zero exit status 1:

error: Package already exists: %package devel

```
When I download the source URLs manually and place the files into the source folder and run docker-rpm-builder without --download-sources parameter, it just runs fine and build correctly.

How to get this working with source downloads in combination with %package sections?

**Comment by alanfranz** [comment]
I think this was fixed with https://github.com/alanfranz/docker-rpm-builder/commit/a428a8b1d4a3ea26140334cedf2e3b622b38d09d

I plan to release a 2.0 of my software within the beginning of next year, stay tuned.

**Comment by alanfranz** [comment]
Consider becoming a docker-rpm-builder developer: https://github.com/alanfranz/docker-rpm-builder/issues/51

**Comment by alanfranz** [comment]
@hunter-nl docker-rpm-builder v1.41 is out and should fix the issue. Check it out if you can.

I'm sorry for the delay: consider contributing to docker-rpm-builder if you actively use it.
