### ISSUE TITLE
Error building rpm from the example

### ISSUE THREAD

**Issue by quicktrick** [alanfranz/docker-rpm-builder#54]
Hello!  Please, don't blame me much, I'm quite a newbie.  I installed drb, run selftest and selftest full.  Then I cloned this repository, cd to `docker-rpm-builder/example/from_dir` and tried to execute 

    docker-rpm-builder dir alanfranz/drb-epel-7-x86-64:latest . /tmp/rpms

with or without `--download-sources` option, the result is always the same:

    Traceback (most recent call last):
      File "/usr/bin/docker-rpm-builder", line 9, in <module>
        load_entry_point('docker-rpm-builder==1.41', 'console_scripts', 'docker-rpm-builder')()
      File "/opt/docker-rpm-builder/lib/python2.7/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/opt/docker-rpm-builder/lib/python2.7/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/opt/docker-rpm-builder/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/opt/docker-rpm-builder/lib/python2.7/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/opt/docker-rpm-builder/lib/python2.7/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/commands/dir.py", line 133, in dir
        rendered_filename = SpecTemplate.from_path(specfile).render(os.environ)
      File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/spectemplate.py", line 46, in render
        with_substitutions = self._ddtemplate.substitute(substitution_mapping).encode("utf-8")
      File "/usr/lib64/python2.7/string.py", line 172, in substitute
        return self.pattern.sub(convert, self.template)
      File "/usr/lib64/python2.7/string.py", line 162, in convert
        val = mapping[named]
      File "/opt/docker-rpm-builder/lib64/python2.7/UserDict.py", line 23, in __getitem__
        raise KeyError(key)
    KeyError: u'ITERATION'

I tried it many times in different combinations.  Where am I wrong?  Could you please give me some points?  Thank you in advance!

**Comment by alanfranz** [comment]
you need to specify such environment variable. The example makes that assumption.

```
ITERATION=123 docker-rpm-builder dir alanfranz/drb-epel-7-x86-64:latest . /tmp/rpms
```

Sorry for the late response, I'm looking for collaborators.

**Comment by quicktrick** [comment]
Thank you very much, @alanfranz !
